import type { Metadata } from "next";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AuthProvider } from "./ui/pages/context/authContext";
import { Layout } from "antd";
import { MenuLayout } from "./ui/pages/MenuLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >


        <AntdRegistry>
          <AuthProvider>
            <Layout style={{ minHeight: '100vh' }}>
              <MenuLayout />
              {children}
            </Layout>
          </AuthProvider>

        </AntdRegistry>

      </body>
    </html>
  );
}
